services:
  # Main monitoring system service
  - type: web
    name: betting-monitor
    env: docker
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: ENABLE_NOTIFICATIONS
        value: false
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: MONGODB_URI
        sync: false
    autoDeploy: true
    healthCheckPath: /api/status 