services:
  # Main monitoring system service
  - type: web
    name: betting-monitor
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm run concurrent-monitor
    envVars:
      - key: NODE_ENV
        value: production
      - key: ENABLE_NOTIFICATIONS
        value: false
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: MONGODB_URI
        sync: false
    autoDeploy: true
    healthCheckPath: /api/status

  # Cricket API service  
  - type: web
    name: cricket-api
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm run cricket-api
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
    autoDeploy: true
    healthCheckPath: /health 