services:
  # Main monitoring system service
  - type: web
    name: betting-monitor
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm run concurrent-monitor
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_PORT
        value: 3000
      - key: ENABLE_NOTIFICATIONS
        value: false
    autoDeploy: true
    healthCheckPath: /api/status

  # Cricket API service  
  - type: web
    name: cricket-api
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm run cricket-api
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3005
    autoDeploy: true
    healthCheckPath: /health

databases:
  # MongoDB database (if using Render's database service)
  - name: cricket-data-db
    databaseName: cricket_data
    plan: starter 