services:
  # A web service for the cricket API
  - type: web
    name: cricket-api
    env: docker
    repo: https://github.com/Anumaantech/BetOdds.git # Replace with your repository URL
    dockerfilePath: ./Dockerfile
    plan: free # Or your desired plan
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    dockerCommand: npm run cricket-api

  # A background worker for the monitoring process
  - type: worker
    name: concurrent-monitor
    env: docker
    repo: https://github.com/Anumaantech/BetOdds.git # Replace with your repository URL
    dockerfilePath: ./Dockerfile
    plan: starter # Or your desired plan
    envVars:
      - key: NODE_ENV
        value: production
    dockerCommand: npm run concurrent-monitor 